### ISSUE TITLE
Nginx invalid state if certs don't exist

### ISSUE THREAD

**Issue by emcniece** [CausticLab/rgon-proxy#17]
Beta tester hit a condition where `rgon.ssl=true` and `rgon.redirect=https` were set, but the SSL directive wasn't printed because the certificates were named differently than what we expect.

```
{{- if eq ($serv.Labels.GetValue "rgon.redirect") "https" }}
  return 301 https://{{$labelValue}}$request_uri;
{{ else }}
  location / {
    proxy_pass http://{{$labelValue}};
  }
{{ end -}}

...
{{- if and (exists (printf "/etc/nginx/certs/%s/fullchain" $labelValue)) (exists (printf "/etc/nginx/certs/%s/privkey" $labelValue)) }}
server {
  server_name {{ $labelValue }};
  listen 443 ssl http2 ;
...
```

The top `rgon.redirect` check should also include a cert presence check in order to prevent the absence of a `proxy_pass: [upstream];` block.

**Comment by Munsio** [comment]
i will try to implement this feature along with #8

**Comment by emcniece** [comment]
Resolved in https://github.com/CausticLab/rgon-proxy/pull/22
