### ISSUE TITLE
Add LE TOS agreement to Rancher questions

### ISSUE THREAD

**Issue by emcniece** [CausticLab/rgon-proxy#19]
Inspired by https://github.com/hlandau/acme/issues/200, users should be able to agree to the TOS before using. This means that the TOS should be easily accessible (perhaps as a link in the catalog description), and this yes/no field should be required.

I don't think this option needs to do anything other than inform users.

**Comment by Munsio** [comment]
I will implement this in the catalog template and pass it as ENV var
