### ISSUE TITLE
How to provide nginx configuration?

### ISSUE THREAD

**Issue by Ramblurr** [CausticLab/rgon-proxy#28]
I need to provide additional configuration for some hostnames.

For example, I need to change the `client_max_body_size` nginx option to allow uploading of large files.

This was well documented in the old docker-gen stack, but rgon is new so the docs don't exist yet.

Where can I add the `client_max_body_size` option on a per host basis?

**Comment by Ramblurr** [comment]
I poked around the code and figured it out myself:


Simply place a file with the same name as the domain in the`vhost/` directory of the rgon-proxy config on the host. In my case the file contained just the single `client_max_body_size` line.

**Comment by Munsio** [comment]
@Ramblurr you are right.
There are multiple possible solutions for that.

In general the flow is as following:
We check some files under the `/etc/nginx/vhost.d/` directory

Server Directive:
1) Check if there is a `default` file and include that - in this default file you can specify something like `server_tokens on;` and so on
2) Check if there is a `[domain]` file and include that - if an domain specific file is present the nginx server will not include the default one you have to do this by yourself - note here if you use multiple domains the first one is used for that check

Location Directive:
1)  Check if there is a `default_location` file - you can probably think where this leads
2) Check if there is a `[domain]_location` file - same here

I try to release at least an small documentation in the next few weeks but im really busy at the moment so i cant guarantee anything.
