### ISSUE TITLE
Proposal: Nginx monitoring

### ISSUE THREAD

**Issue by emcniece** [CausticLab/rgon-proxy#35]
It would be neat to have some built-in status charts. https://sysdig.com/blog/monitor-nginx-kubernetes/

**Comment by Munsio** [comment]
Okay, this is something you can do right now with the domain specific config.
But it would also be possible to add this with an label or something like that.
Or did you thought of an other way to integrate?

**Comment by emcniece** [comment]
Yeah, I think it could be part of the rancher-gen.cfg that gets enabled when a domain label is present. Confirmed that the Nginx we run has the `http_sub_module` enabled.

I did a quick search for charts/dashboards and there are lots of enterprise solutions but I didn't see anything small or open-source. We might have to write a small web interface to display collected data, and that's a project by itself.

**Comment by Munsio** [comment]
Trust me thats definitly to much todo if you want to build that for yourself.
There are plenty of opensource products out there like the [ELK Stack](https://www.elastic.co/webinars/introduction-elk-stack) or [Grafana + InfluxDB + CollectD](https://sonnguyen.ws/monitor-nginx-collectd-influxdb-grafana/)
