### ISSUE TITLE
Server weight

### ISSUE THREAD

**Issue by Munsio** [CausticLab/rgon-proxy#41]
In nginx it is possible to set an weight definition for upstream servers, maybe we can add an `rgon.weight` label on single containers to enable that behaviour.

More information: http://nginx.org/en/docs/http/load_balancing.html#nginx_weighted_load_balancing

Polling with 👍 and 👎

**Comment by emcniece** [comment]
Added in https://github.com/CausticLab/rgon-proxy/pull/50
