### ISSUE TITLE
Add nginx.conf vhost override capability

### ISSUE THREAD

**Issue by emcniece** [CausticLab/rgon-proxy#7]
`gzip_types` should be moved to the `server{}` scope. 

Implement vhost file inclusion: [example](https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/blob/master/app/nginx.tmpl#L186-L190)

**Comment by Munsio** [comment]
https://github.com/CausticLab/rgon-proxy/blob/dev/examples/rancher-gen/nginx.tmpl#L162-L166
this is already in the template so we can close this one

**Comment by emcniece** [comment]
Should we still move `gzip_types` into the `server{}` directive?

**Comment by Munsio** [comment]
as i told - per default i would remove this from the template himself and add it maybe in the default one cause sometimes those gzip things can break stuff.

Also a paramter we have forgotten is server_tokens off; to not display nginx server-version on error sites
