### ISSUE TITLE
Create template block for nginx.tmpl

### ISSUE THREAD

**Issue by emcniece** [CausticLab/rgon-proxy#8]
Create a template block so that the 80/443 config can be referenced from both HOST and SERVICE loops. [Example](https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/blob/master/app/nginx.tmpl)

**Comment by emcniece** [comment]
As noted in https://github.com/CausticLab/rgon-proxy/pull/22, the `dict` keyword is not available in our text templates. Since we 1) don't have much template duplication, 2) don't need to iterate over containers and hosts, and 3) I am not sure how to implement `dict`, I am in favour of closing this issue.

**Comment by Munsio** [comment]
closed and maybe reopened later if we find a case for this

**Comment by emcniece** [comment]
Re-opening because @Munsio is right and we need a Host SSL block so it's a good idea to template this out!

**Comment by Munsio** [comment]
related pull-request #27

**Comment by Munsio** [comment]
feature is implemented in the `dev` branch
